Repository UMC-Matching-Center/U.M.C_Web, pull requests merged in 2024-02, with the labels that each got.

#42 38 지원 현황 보기
  src/common/Navbar/PMNavbar.jsx
  src/components/Modal/Modal.css
  src/components/Modal/ViewStatusModal.jsx
  src/components/viewstatus/ViewBody.jsx
  src/components/viewstatus/ViewHeader.jsx
  src/components/viewstatus/ViewSelect.jsx
  src/pages/myProject/MyProject.jsx
  src/pages/myProject/viewstatus/ViewStatus.jsx
Labels: ✨ Dev

#47 43 일정 관리 api연결
  src/api/index.js
  src/api/scheduleAPI.js
  src/components/schedule/CustomCalendar.jsx
  src/components/schedule/ScheduleList.jsx
  src/components/schedule/ScheduleMonth.jsx
  src/components/schedule/schedulelist/ScheduleAdd.jsx
  src/components/schedule/schedulelist/ScheduleDetail.css
  src/components/schedule/schedulelist/ScheduleDetail.jsx
  src/components/schedule/schedulelist/ScheduleEdit.jsx
  src/components/schedule/schedulelist/dotoptions/DotAddOptions.jsx
  src/components/schedule/schedulelist/dotoptions/DotEditOptions.jsx
  src/pages/schedule/Schedule.jsx
Labels: ♻️ Refactor, 🔔 API

#48 44 챌린저 API 연결
  src/api/challengerAPI.js
  src/api/index.js
  src/api/mypageAPI.js
  src/common/Navbar/Navbar.css
  src/common/Selectbox/RoundSelectBox.jsx
  src/components/Modal/ChallengerExpel.jsx
  src/components/Modal/SignupAccept.jsx
  src/components/Modal/SignupReject.jsx
  src/components/Modal/index.js
  src/pages/challenger/Challenger.css
  src/pages/challenger/ChallengerManage.jsx
  src/pages/challenger/ChallengerNew.jsx
  src/pages/myPage/MyPageAdmin.jsx
  src/pages/myPage/MyPageUser.jsx
  src/utils/cookies.js
  src/utils/customAxios.js
  src/utils/intersectionObserve.js
Labels: 🔔 API

#53 49 지원 현황 보기 api
  src/api/index.js
  src/api/viewstatusAPI.js
  src/common/Navbar/Navbar.jsx
  src/components/modal/ViewStatusModal.jsx
  src/components/viewstatus/ViewBody.jsx
  src/components/viewstatus/ViewHeader.jsx
  src/components/viewstatus/ViewSelect.jsx
  src/pages/myProject/viewstatus/ViewStatus.jsx
Labels: 🔔 API

#52 51 footer 및 회원가입마이페이지 수정
  public/android-chrome-192x192.png
  public/android-chrome-512x512.png
  public/apple-touch-icon.png
  public/browserconfig.xml
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  public/index.html
  public/manifest.json
  public/mstile-144x144.png
  public/mstile-150x150.png
  public/mstile-310x150.png
  public/mstile-310x310.png
  public/mstile-70x70.png
  public/safari-pinned-tab.svg
  public/site.webmanifest
  src/App.js
  src/api/mypageAPI.js
  src/common/Footer/Footer.css
  src/common/Footer/Footer.jsx
  src/common/Navbar/Navbar.css
  src/components/modal/ChallengerExpel.jsx
  src/components/modal/Logout.jsx
  src/components/modal/SignupAccept.jsx
  src/components/modal/SignupComplete.jsx
  src/components/modal/SignupReject.jsx
  src/pages/Home.css
  src/pages/Home.jsx
  src/pages/challenger/Challenger.css
  src/pages/challenger/ChallengerManage.jsx
  src/pages/myPage/MyPage.css
  src/pages/myPage/MyPageAdmin.jsx
  src/pages/myPage/MyPageUser.jsx
  src/pages/register/Register.css
  src/pages/register/Register.jsx
  src/pages/register/Signup.jsx
  src/pages/register/SignupDetail.jsx
Labels: ✨ Dev

#55 매칭 프로젝트 API
  src/api/index.js
  src/api/matchAPI.js
  src/common/MatchCard/MatchCard.jsx
  src/common/MemberCard/MemberCard.css
  src/common/MemberCard/MemberCard.jsx
  src/common/Navbar/AdminNavbar.jsx
  src/common/Navbar/Navbar.css
  src/common/Navbar/PMNavbar.jsx
  src/common/Navbar/UserNavbar.jsx
  src/components/ProjectDetail.jsx
  src/components/markdownTool/CustomImage.js
  src/components/modal/Apply.jsx
  src/components/modal/Modal.css
  src/components/modal/index.js
  src/context/TextAreaProvider.js
  src/pages/match/Match.jsx
  src/pages/match/MatchDetail.jsx
  src/pages/match/MatchQA.jsx
  src/pages/match/MatchWrite.css
  src/pages/match/MatchWrite.jsx
  src/pages/myProject/LandingPage.jsx
  src/pages/myProject/MyProject.jsx
Labels: ✨ Dev, 🔔 API

#58 매칭 프로젝트 중 지원하기 API
  src/api/index.js
  src/api/matchAPI.js
  src/common/Alarm/AlarmModal.jsx
  src/common/Navbar/AdminNavbar.jsx
  src/common/Navbar/PMNavbar.jsx
  src/common/Navbar/UserNavbar.jsx
  src/components/modal/ApplyError.jsx
  src/components/modal/index.js
  src/pages/match/MatchDetail.jsx
  src/pages/match/MatchWrite.jsx
  src/utils/customAxios.js
Labels: 🔔 API

#60 57 홈페이지 API
  public/manifest.json
  src/App.js
  src/api/errorCode.js
  src/api/index.js
  src/api/obProjectAPI.js
  src/common/OBCard/OBCard.css
  src/common/OBCard/OBCard.jsx
  src/pages/Home.jsx
  src/pages/HomeDetail.jsx
  src/pages/home/Home.css
  src/pages/home/Home.jsx
  src/pages/home/HomeDetail.jsx
Labels: 🔔 API

#70 66 상호 평가 기능추가 및 API 연동
  src/api/evaluateAPI.js
  src/api/index.js
  src/components/evaluate/Evaluate.css
  src/components/evaluate/EvaluateCard.jsx
  src/components/evaluate/EvaluateCardDetail.jsx
  src/components/evaluate/EvaluateStar.jsx
  src/components/evaluate/EvaulateToggle.jsx
  src/components/evaluate/MyEvaluationCard.jsx
  src/pages/myProject/TeamEvaluate.jsx
Labels: ✨ Dev, 🔔 API

#72 71 디자인 일부 수정
  src/common/MatchCard/MatchCard.jsx
  src/common/OBCard/OBCard.css
  src/common/OBCard/OBCard.jsx
  src/components/modal/Modal.css
  src/components/schedule/schedulelist/ScheduleDetail.css
  src/pages/challenger/ChallengerManage.jsx
  src/pages/challenger/ChallengerNew.jsx
  src/pages/match/Match.jsx
  src/pages/match/MatchDetail.jsx
  src/pages/match/MatchWrite.css
  src/pages/match/MatchWrite.jsx
  src/pages/myPage/MyPage.css
  src/pages/myPage/MyPageAdmin.jsx
  src/pages/myPage/MyPageUser.jsx
  src/pages/myProject/landing/LandingPageWrite.jsx
  src/pages/register/Register.css
  src/pages/register/Register.jsx
  src/pages/register/Signup.jsx
  src/pages/register/SignupDetail.jsx
Labels: ✨ Dev

#73 67 알람 API 및 오류 수정
  package.json
  src/api/alramAPI.js
  src/api/index.js
  src/common/Alarm/AlarmModal.jsx
  src/common/Navbar/AdminNavbar.jsx
  src/common/Navbar/PMNavbar.jsx
  src/common/Navbar/UserNavbar.jsx
  src/pages/challenger/ChallengerManage.jsx
  src/pages/challenger/ChallengerNew.jsx
  src/pages/home/Home.jsx
  src/pages/match/Match.jsx
  src/utils/customAxios.js
  yarn.lock
Labels: 🐞 Fix, 🔔 API

#77 🐞 Fix: 같은 css 이름으로 인한 css 중복 문제 해결
  src/components/evaluate/Evaluate.css
  src/components/evaluate/EvaluateCardDetail.jsx
  src/components/evaluate/MyEvaluationCard.jsx
  src/pages/challenger/Challenger.css
  src/pages/myPage/MyPage.css
Labels: 🐞 Fix

#80 디자인 수정 및 홈페이지 MemberCard 추가
  src/api/landingAPI.js
  src/common/MemberCard/MemberCard.jsx
  src/common/Navbar/PMNavbar.jsx
  src/components/ProjectDetail.jsx
  src/pages/match/MatchQA.jsx
  src/pages/match/MatchWrite.jsx
  src/pages/myPage/MyPageUser.jsx
  src/pages/myProject/landing/LandingPage.jsx
  src/pages/notice/NoticeDetail.jsx
Labels: 🐞 Fix, ✨ Dev, ♻️ Refactor

#83 🐞 Fix: 알림 존재 표기 에러 해결
  src/common/Navbar/AdminNavbar.jsx
  src/common/Navbar/PMNavbar.jsx
  src/common/Navbar/UserNavbar.jsx
Labels: 🐞 Fix

#88 Q&A디자인 수정
  src/pages/match/MatchDetail.jsx
  src/pages/match/MatchQA.jsx
Labels: ♻️ Refactor

#91 Main) toastify 에러 방지
  src/common/Navbar/AdminNavbar.jsx
  src/common/Navbar/PMNavbar.jsx
  src/common/Navbar/UserNavbar.jsx
  src/components/evaluate/EvaluateCard.jsx
  src/components/schedule/ScheduleList.jsx
  src/components/schedule/schedulelist/ScheduleEdit.jsx
  src/pages/challenger/ChallengerManage.jsx
  src/pages/challenger/ChallengerNew.jsx
  src/pages/match/Match.jsx
  src/pages/match/MatchDetail.jsx
  src/pages/match/MatchQA.jsx
  src/pages/myPage/MyPageAdmin.jsx
  src/pages/myPage/MyPageUser.jsx
  src/pages/myProject/ApplyStatus.jsx
  src/pages/myProject/TeamEvaluate.jsx
  src/pages/myProject/landing/LandingPage.jsx
  src/pages/register/Register.jsx
  src/pages/register/SignupDetail.jsx
Labels: 🐞 Fix

#92 🐞 Fix: 매칭 페이지 Loading 상태 변경 함수 위치 변경
  src/pages/match/Match.jsx
Labels: 🐞 Fix
